on:
  schedule:
    - cron: '30 4 * * *'  # rebuild daily at 4:30 UTC
  workflow_dispatch:

name: sync

jobs:
  sync:
    runs-on: [ubuntu-latest]
    permissions:
      # for commit changes
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false

    - name: snapshot repo
      run: |
          uvx --from ida-hcli hcli plugin --repo github repo snapshot > plugin-repository.json
          cat plugin-repository.json
          git diff plugin-repository.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HCLI_DISABLE_UPDATES: 1
        TTY_COMPATIBLE: 0
        TTY_INTERACTIVE: 0

    - name: commit
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "Hex-Rays (GH Action)"
        git add plugin-repository.json
        git commit -m "sync plugin-repository.json" || echo "no changes"

    - name: push
      uses: ad-m/github-push-action@master
